/**
 * Complete list of 192 countries with phone country codes and digit requirements
 * Used for phone number validation in Locations & Rooms page
 */

export interface CountryPhoneCode {
    code: string
    country: string
    digits: number
    flag?: string
}

export const COUNTRY_PHONE_CODES: CountryPhoneCode[] = [
    { code: '+1', country: 'United States', digits: 10 },
    { code: '+1', country: 'Canada', digits: 10 },
    { code: '+1', country: 'Bahamas', digits: 10 },
    { code: '+1', country: 'Barbados', digits: 10 },
    { code: '+1', country: 'Bermuda', digits: 10 },
    { code: '+1', country: 'Dominican Republic', digits: 10 },
    { code: '+1', country: 'Jamaica', digits: 10 },
    { code: '+1', country: 'Puerto Rico', digits: 10 },
    { code: '+1', country: 'Trinidad and Tobago', digits: 10 },
    { code: '+7', country: 'Russia', digits: 10 },
    { code: '+7', country: 'Kazakhstan', digits: 10 },
    { code: '+20', country: 'Egypt', digits: 10 },
    { code: '+27', country: 'South Africa', digits: 9 },
    { code: '+30', country: 'Greece', digits: 10 },
    { code: '+31', country: 'Netherlands', digits: 9 },
    { code: '+32', country: 'Belgium', digits: 9 },
    { code: '+33', country: 'France', digits: 9 },
    { code: '+34', country: 'Spain', digits: 9 },
    { code: '+36', country: 'Hungary', digits: 9 },
    { code: '+39', country: 'Italy', digits: 10 },
    { code: '+40', country: 'Romania', digits: 9 },
    { code: '+41', country: 'Switzerland', digits: 9 },
    { code: '+43', country: 'Austria', digits: 10 },
    { code: '+44', country: 'United Kingdom', digits: 10 },
    { code: '+45', country: 'Denmark', digits: 8 },
    { code: '+46', country: 'Sweden', digits: 9 },
    { code: '+47', country: 'Norway', digits: 8 },
    { code: '+48', country: 'Poland', digits: 9 },
    { code: '+49', country: 'Germany', digits: 10 },
    { code: '+51', country: 'Peru', digits: 9 },
    { code: '+52', country: 'Mexico', digits: 10 },
    { code: '+53', country: 'Cuba', digits: 8 },
    { code: '+54', country: 'Argentina', digits: 10 },
    { code: '+55', country: 'Brazil', digits: 11 },
    { code: '+56', country: 'Chile', digits: 9 },
    { code: '+57', country: 'Colombia', digits: 10 },
    { code: '+58', country: 'Venezuela', digits: 10 },
    { code: '+60', country: 'Malaysia', digits: 9 },
    { code: '+61', country: 'Australia', digits: 9 },
    { code: '+62', country: 'Indonesia', digits: 10 },
    { code: '+63', country: 'Philippines', digits: 10 },
    { code: '+64', country: 'New Zealand', digits: 9 },
    { code: '+65', country: 'Singapore', digits: 8 },
    { code: '+66', country: 'Thailand', digits: 9 },
    { code: '+81', country: 'Japan', digits: 10 },
    { code: '+82', country: 'South Korea', digits: 10 },
    { code: '+84', country: 'Vietnam', digits: 9 },
    { code: '+86', country: 'China', digits: 11 },
    { code: '+90', country: 'Turkey', digits: 10 },
    { code: '+91', country: 'India', digits: 10 },
    { code: '+92', country: 'Pakistan', digits: 10 },
    { code: '+93', country: 'Afghanistan', digits: 9 },
    { code: '+94', country: 'Sri Lanka', digits: 9 },
    { code: '+95', country: 'Myanmar', digits: 9 },
    { code: '+98', country: 'Iran', digits: 10 },
    { code: '+212', country: 'Morocco', digits: 9 },
    { code: '+213', country: 'Algeria', digits: 9 },
    { code: '+216', country: 'Tunisia', digits: 8 },
    { code: '+218', country: 'Libya', digits: 9 },
    { code: '+220', country: 'Gambia', digits: 7 },
    { code: '+221', country: 'Senegal', digits: 9 },
    { code: '+222', country: 'Mauritania', digits: 8 },
    { code: '+223', country: 'Mali', digits: 8 },
    { code: '+224', country: 'Guinea', digits: 9 },
    { code: '+225', country: 'Ivory Coast', digits: 10 },
    { code: '+226', country: 'Burkina Faso', digits: 8 },
    { code: '+227', country: 'Niger', digits: 8 },
    { code: '+228', country: 'Togo', digits: 8 },
    { code: '+229', country: 'Benin', digits: 8 },
    { code: '+230', country: 'Mauritius', digits: 8 },
    { code: '+231', country: 'Liberia', digits: 8 },
    { code: '+232', country: 'Sierra Leone', digits: 8 },
    { code: '+233', country: 'Ghana', digits: 9 },
    { code: '+234', country: 'Nigeria', digits: 10 },
    { code: '+235', country: 'Chad', digits: 8 },
    { code: '+236', country: 'Central African Republic', digits: 8 },
    { code: '+237', country: 'Cameroon', digits: 9 },
    { code: '+238', country: 'Cape Verde', digits: 7 },
    { code: '+239', country: 'São Tomé and Príncipe', digits: 7 },
    { code: '+240', country: 'Equatorial Guinea', digits: 9 },
    { code: '+241', country: 'Gabon', digits: 8 },
    { code: '+242', country: 'Republic of the Congo', digits: 9 },
    { code: '+243', country: 'Democratic Republic of the Congo', digits: 9 },
    { code: '+244', country: 'Angola', digits: 9 },
    { code: '+245', country: 'Guinea-Bissau', digits: 7 },
    { code: '+246', country: 'Diego Garcia', digits: 7 },
    { code: '+248', country: 'Seychelles', digits: 7 },
    { code: '+249', country: 'Sudan', digits: 9 },
    { code: '+250', country: 'Rwanda', digits: 9 },
    { code: '+251', country: 'Ethiopia', digits: 9 },
    { code: '+252', country: 'Somalia', digits: 8 },
    { code: '+253', country: 'Djibouti', digits: 8 },
    { code: '+254', country: 'Kenya', digits: 9 },
    { code: '+255', country: 'Tanzania', digits: 9 },
    { code: '+256', country: 'Uganda', digits: 9 },
    { code: '+257', country: 'Burundi', digits: 8 },
    { code: '+258', country: 'Mozambique', digits: 9 },
    { code: '+260', country: 'Zambia', digits: 9 },
    { code: '+261', country: 'Madagascar', digits: 9 },
    { code: '+262', country: 'Réunion', digits: 9 },
    { code: '+263', country: 'Zimbabwe', digits: 9 },
    { code: '+264', country: 'Namibia', digits: 9 },
    { code: '+265', country: 'Malawi', digits: 9 },
    { code: '+266', country: 'Lesotho', digits: 8 },
    { code: '+267', country: 'Botswana', digits: 8 },
    { code: '+268', country: 'Eswatini', digits: 8 },
    { code: '+290', country: 'Saint Helena', digits: 4 },
    { code: '+291', country: 'Eritrea', digits: 7 },
    { code: '+297', country: 'Aruba', digits: 7 },
    { code: '+298', country: 'Faroe Islands', digits: 6 },
    { code: '+299', country: 'Greenland', digits: 6 },
    { code: '+350', country: 'Gibraltar', digits: 8 },
    { code: '+351', country: 'Portugal', digits: 9 },
    { code: '+352', country: 'Luxembourg', digits: 9 },
    { code: '+353', country: 'Ireland', digits: 9 },
    { code: '+354', country: 'Iceland', digits: 7 },
    { code: '+355', country: 'Albania', digits: 9 },
    { code: '+356', country: 'Malta', digits: 8 },
    { code: '+357', country: 'Cyprus', digits: 8 },
    { code: '+358', country: 'Finland', digits: 9 },
    { code: '+359', country: 'Bulgaria', digits: 9 },
    { code: '+370', country: 'Lithuania', digits: 8 },
    { code: '+371', country: 'Latvia', digits: 8 },
    { code: '+372', country: 'Estonia', digits: 8 },
    { code: '+373', country: 'Moldova', digits: 8 },
    { code: '+374', country: 'Armenia', digits: 8 },
    { code: '+375', country: 'Belarus', digits: 9 },
    { code: '+376', country: 'Andorra', digits: 6 },
    { code: '+377', country: 'Monaco', digits: 8 },
    { code: '+378', country: 'San Marino', digits: 10 },
    { code: '+380', country: 'Ukraine', digits: 9 },
    { code: '+381', country: 'Serbia', digits: 9 },
    { code: '+382', country: 'Montenegro', digits: 8 },
    { code: '+383', country: 'Kosovo', digits: 8 },
    { code: '+385', country: 'Croatia', digits: 9 },
    { code: '+386', country: 'Slovenia', digits: 9 },
    { code: '+387', country: 'Bosnia and Herzegovina', digits: 8 },
    { code: '+389', country: 'North Macedonia', digits: 8 },
    { code: '+420', country: 'Czech Republic', digits: 9 },
    { code: '+421', country: 'Slovakia', digits: 9 },
    { code: '+423', country: 'Liechtenstein', digits: 7 },
    { code: '+500', country: 'Falkland Islands', digits: 5 },
    { code: '+501', country: 'Belize', digits: 7 },
    { code: '+502', country: 'Guatemala', digits: 8 },
    { code: '+503', country: 'El Salvador', digits: 8 },
    { code: '+504', country: 'Honduras', digits: 8 },
    { code: '+505', country: 'Nicaragua', digits: 8 },
    { code: '+506', country: 'Costa Rica', digits: 8 },
    { code: '+507', country: 'Panama', digits: 8 },
    { code: '+508', country: 'Saint Pierre and Miquelon', digits: 6 },
    { code: '+509', country: 'Haiti', digits: 8 },
    { code: '+590', country: 'Guadeloupe', digits: 9 },
    { code: '+591', country: 'Bolivia', digits: 8 },
    { code: '+592', country: 'Guyana', digits: 7 },
    { code: '+593', country: 'Ecuador', digits: 9 },
    { code: '+594', country: 'French Guiana', digits: 9 },
    { code: '+595', country: 'Paraguay', digits: 9 },
    { code: '+596', country: 'Martinique', digits: 9 },
    { code: '+597', country: 'Suriname', digits: 7 },
    { code: '+598', country: 'Uruguay', digits: 8 },
    { code: '+599', country: 'Curaçao', digits: 7 },
    { code: '+670', country: 'East Timor', digits: 8 },
    { code: '+672', country: 'Norfolk Island', digits: 6 },
    { code: '+673', country: 'Brunei', digits: 7 },
    { code: '+674', country: 'Nauru', digits: 7 },
    { code: '+675', country: 'Papua New Guinea', digits: 8 },
    { code: '+676', country: 'Tonga', digits: 7 },
    { code: '+677', country: 'Solomon Islands', digits: 7 },
    { code: '+678', country: 'Vanuatu', digits: 7 },
    { code: '+679', country: 'Fiji', digits: 7 },
    { code: '+680', country: 'Palau', digits: 7 },
    { code: '+681', country: 'Wallis and Futuna', digits: 6 },
    { code: '+682', country: 'Cook Islands', digits: 5 },
    { code: '+683', country: 'Niue', digits: 4 },
    { code: '+684', country: 'American Samoa', digits: 7 },
    { code: '+685', country: 'Samoa', digits: 7 },
    { code: '+686', country: 'Kiribati', digits: 5 },
    { code: '+687', country: 'New Caledonia', digits: 6 },
    { code: '+688', country: 'Tuvalu', digits: 5 },
    { code: '+689', country: 'French Polynesia', digits: 8 },
    { code: '+690', country: 'Tokelau', digits: 4 },
    { code: '+691', country: 'Micronesia', digits: 7 },
    { code: '+692', country: 'Marshall Islands', digits: 7 },
    { code: '+850', country: 'North Korea', digits: 10 },
    { code: '+852', country: 'Hong Kong', digits: 8 },
    { code: '+853', country: 'Macau', digits: 8 },
    { code: '+855', country: 'Cambodia', digits: 9 },
    { code: '+856', country: 'Laos', digits: 9 },
    { code: '+880', country: 'Bangladesh', digits: 10 },
    { code: '+886', country: 'Taiwan', digits: 9 },
    { code: '+960', country: 'Maldives', digits: 7 },
    { code: '+961', country: 'Lebanon', digits: 8 },
    { code: '+962', country: 'Jordan', digits: 9 },
    { code: '+963', country: 'Syria', digits: 9 },
    { code: '+964', country: 'Iraq', digits: 10 },
    { code: '+965', country: 'Kuwait', digits: 8 },
    { code: '+966', country: 'Saudi Arabia', digits: 9 },
    { code: '+967', country: 'Yemen', digits: 9 },
    { code: '+968', country: 'Oman', digits: 8 },
    { code: '+970', country: 'Palestine', digits: 9 },
    { code: '+971', country: 'United Arab Emirates', digits: 9 },
    { code: '+972', country: 'Israel', digits: 9 },
    { code: '+973', country: 'Bahrain', digits: 8 },
    { code: '+974', country: 'Qatar', digits: 8 },
    { code: '+975', country: 'Bhutan', digits: 8 },
    { code: '+976', country: 'Mongolia', digits: 8 },
    { code: '+977', country: 'Nepal', digits: 10 },
    { code: '+992', country: 'Tajikistan', digits: 9 },
    { code: '+993', country: 'Turkmenistan', digits: 8 },
    { code: '+994', country: 'Azerbaijan', digits: 9 },
    { code: '+995', country: 'Georgia', digits: 9 },
    { code: '+996', country: 'Kyrgyzstan', digits: 9 },
    { code: '+998', country: 'Uzbekistan', digits: 9 },
]

/**
 * Get country details by phone code
 */
export function getCountryByCode(code: string): CountryPhoneCode | undefined {
    return COUNTRY_PHONE_CODES.find(c => c.code === code)
}

/**
 * Get all unique country codes
 */
export function getUniqueCodes(): string[] {
    return Array.from(new Set(COUNTRY_PHONE_CODES.map(c => c.code))).sort()
}

/**
 * Get countries for a specific code
 */
export function getCountriesByCode(code: string): CountryPhoneCode[] {
    return COUNTRY_PHONE_CODES.filter(c => c.code === code)
}

/**
 * Search countries by name or code
 */
export function searchCountries(query: string): CountryPhoneCode[] {
    const q = query.toLowerCase()
    return COUNTRY_PHONE_CODES.filter(c =>
        c.country.toLowerCase().includes(q) || c.code.includes(q)
    )
}
